#!/bin/bash
# This script launches the CLAM create_patches_fp.py job after slides have been triaged.

set -euo pipefail

# --- Configuration Variables ---

# 1. Paths and Directories
# Path to the detailed CSV report generated by the Python script
CSV_REPORT="/path/to/your/wsi_detailed_report.csv" 
# Root directory where the triage script will create symlinked folders
TRIAGE_ROOT="./triage_workspace"
# Base directory where CLAM will save the output features and patches
SAVE_DIR_BASE="./CPTAC_COAD/COAD-features"
# Path to the CLAM repository directory
CLAM_DIR="./CLAM"

# 2. Desired Output Patch Sizes
# These are the *effective* patch sizes you want after accounting for downsampling.
OUTPUT_PATCH_SIZES=("224" "256" "512")

# 3. CLAM Script Parameters
SEG=true
PATCH=true
STITCH=false
NO_AUTO_SKIP=true # Set to false to skip already processed files
PRESET="tcga.csv" # e.g., "bwh_resection.csv", "tcga.csv", or ""

# --- Script Logic ---

echo "### STAGE 1: TRIAGING SLIDES ###"
# First, run the triage script to create the organized symlink directories.
python3 triage_slides.py --csv "$CSV_REPORT" --output "$TRIAGE_ROOT"
echo "Triage complete. Symlinks created in $TRIAGE_ROOT"
echo "--------------------------------------------------"

echo "### STAGE 2: PROCESSING TRIAGED DIRECTORIES ###"
cd "$CLAM_DIR"

# Check if there are any directories to process
if [ -z "$(ls -A $TRIAGE_ROOT)" ]; then
    echo "No triage directories found in $TRIAGE_ROOT. Exiting."
    exit 0
fi

# Iterate over each triage directory (e.g., 20x_native, 10x_from_40x_ds4, etc.)
for source_dir in "$TRIAGE_ROOT"/*; do
    if [ -d "$source_dir" ]; then
        dir_name=$(basename "$source_dir")
        echo "Processing directory: $dir_name"

        # --- Parse strategy from directory name ---
        # Example: 10x_from_40x_ds4 -> target_mag=10x, source_mag=40x, downsample=4
        # Example: 20x_native       -> target_mag=20x, source_mag=20x, downsample=1
        
        target_mag=$(echo "$dir_name" | cut -d'_' -f1)
        
        if [[ $dir_name == *"_native"* ]]; then
            downsample_factor=1
        else
            downsample_factor=$(echo "$dir_name" | grep -o 'ds[0-9]*' | cut -c 3-)
        fi
        
        if [ -z "$downsample_factor" ]; then
            echo "Warning: Could not determine downsample factor for $dir_name. Skipping."
            continue
        fi

        # --- Loop through desired patch sizes and run CLAM ---
        for output_size in "${OUTPUT_PATCH_SIZES[@]}"; do
        
            # Calculate the actual patch size for extraction
            # If downsampling by 2x, we need to extract a 2x larger patch.
            extraction_size=$((output_size * downsample_factor))
            
            # Define a unique save directory for this configuration
            save_dir="$SAVE_DIR_BASE/${target_mag}/patch_${output_size}"
            mkdir -p "$save_dir"

            # --- Construct the CLAM Command ---
            declare -a ARGS
            ARGS+=("--source" "$source_dir")
            ARGS+=("--save_dir" "$save_dir")
            ARGS+=("--patch_size" "$extraction_size")
            ARGS+=("--step_size" "$extraction_size") # Step size = patch size for non-overlapping patches
            
            # Only add custom_downsample if we are actually downsampling
            if [ "$downsample_factor" -gt 1 ]; then
                ARGS+=("--custom_downsample" "$downsample_factor")
            fi
            
            $PATCH && ARGS+=("--patch")
            $SEG && ARGS+=("--seg")
            $STITCH && ARGS+=("--stitch")
            $NO_AUTO_SKIP || ARGS+=("--no_auto_skip")
            [ -n "$PRESET" ] && ARGS+=("--preset" "$PRESET")

            echo
            echo "Starting CLAM job for:"
            echo "  - Target Magnification: $target_mag"
            echo "  - Effective Patch Size: $output_size"
            echo "  - Source Directory: $dir_name"
            echo "  - Extraction Patch Size: $extraction_size"
            echo "  - Downsample Factor: $downsample_factor"
            echo "  - Save Directory: $save_dir"
            echo "Command:"
            echo "python create_patches_fp.py ${ARGS[@]}"
            echo "----------------------------------------"
            
            # Execute the command
            python create_patches_fp.py "${ARGS[@]}"
            
            echo "----------------------------------------"
            echo "Job for patch size $output_size completed."
            echo
        done
    fi
done

echo "##################################################"
echo "All CLAM patch extraction jobs completed."
echo "##################################################"
